# Generated by Django 5.1.4 on 2025-10-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='items',
            field=models.ManyToManyField(to='adminapp.tblmenuitem'),
        ),
    ]
