# Generated by Django 5.1.4 on 2025-10-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_dailymenu_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldailymenu',
            name='items',
            field=models.ManyToManyField(to='adminapp.tblmenuitem'),
        ),
    ]
