# Generated by Django 5.2.10 on 2026-01-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_todaysspecial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todaysspecial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='todays_special/'),
        ),
    ]
