# Generated by Django 5.1.4 on 2025-10-22 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_tbldailymenu_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='booking_price',
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('seat_price', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='adminapp.table')),
            ],
            options={
                'unique_together': {('table', 'seat_number')},
            },
        ),
    ]
