# Generated by Django 5.2.10 on 2026-02-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_todaysspecial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_todays_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='special_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='items',
            field=models.ManyToManyField(to='adminapp.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
