# Generated by Django 5.1.4 on 2025-10-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_table_booking_price_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
