# Generated by Django 5.2.10 on 2026-02-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_migrate_todays_special_to_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_price',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=6),
        ),
    ]
