# Generated by Django 5.1.3 on 2025-11-21 09:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporttbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], max_length=10)),
                ('batch_name', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_date', models.DateField()),
                ('num_persons', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbltimeslot')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='userapp.feedback')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblmenuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outsider_name', models.CharField(blank=True, max_length=100, null=True)),
                ('outsider_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('booking_type', models.CharField(blank=True, choices=[('TABLE_ONLY', 'Table Only'), ('PREBOOKED', 'Prebooked (Table + Food)'), ('ONSPOT', 'On-the-Spot (Table + Food)')], max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('number_of_persons', models.PositiveIntegerField(blank=True, null=True)),
                ('tables', models.JSONField(blank=True, default=list)),
                ('table_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_mode', models.CharField(default='POS', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.category')),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbltimeslot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.tbluser')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.order'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblmenuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='userapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_seats', to='userapp.order')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.seat')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('card', 'Card')], max_length=10)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cardholder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=5, null=True)),
                ('cvv_number', models.CharField(blank=True, max_length=4, null=True)),
                ('payment_status', models.CharField(default='success', max_length=50)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='userapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='ReprotTblImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_report_images/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_images', to='userapp.reporttbl')),
            ],
        ),
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('booking_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.seat')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.tbluser')),
            ],
        ),
        migrations.AddField(
            model_name='reporttbl',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.tbluser'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.tbluser'),
        ),
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.category')),
                ('selected_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblmenuitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.tbluser')),
            ],
        ),
    ]
