# Generated by Django 5.1.3 on 2025-11-14 08:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='rating',
            new_name='overall_rating',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feedback',
        ),
        migrations.AddField(
            model_name='feedback',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FeedbackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='userapp.feedback')),
            ],
        ),
    ]
