# Generated by Django 5.1.3 on 2025-11-14 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('userapp', '0002_rename_rating_feedback_overall_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackitem',
            name='food_name',
        ),
        migrations.AddField(
            model_name='feedbackitem',
            name='food_item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblmenuitem'),
            preserve_default=False,
        ),
    ]
