# Generated by Django 5.2.10 on 2026-01-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_tbluser_registered_at_tbluser_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
