# Generated by Django 5.1.3 on 2025-11-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_order_outsider_name_order_outsider_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='booking_type',
            field=models.CharField(blank=True, choices=[('TABLE_ONLY', 'Table Only'), ('PREBOOKED', 'Prebooked (Table + Food)'), ('ONSPOT', 'On-the-Spot (Table + Food)')], max_length=20, null=True),
        ),
    ]
