# Generated by Django 5.1.4 on 2025-10-23 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_seat_is_occupied'),
        ('userapp', '0002_seatbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='userselection',
            name='selected_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblmenuitem'),
        ),
    ]
