# Generated by Django 5.1.3 on 2025-11-21 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_order_booking_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='TblUser',
        ),
    ]
