# Generated by Django 5.1.4 on 2025-10-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_booking_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbooking',
            name='booking_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
