# Generated by Django 5.1.3 on 2025-11-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_feedbackitem_food_name_feedbackitem_food_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='image',
        ),
    ]
