# Generated by Django 5.2.10 on 2026-01-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_order_food_payment_mode_order_food_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('table', 'Table Payment'), ('both', 'Table + Food Payment')], default='both', max_length=10),
        ),
    ]
