# Generated by Django 5.2.10 on 2026-01-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_payment_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_mode',
        ),
        migrations.AlterField(
            model_name='order',
            name='food_payment_mode',
            field=models.CharField(choices=[('upi', 'UPI'), ('card', 'Card'), ('cash', 'Cash')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_payment_mode',
            field=models.CharField(choices=[('upi', 'UPI'), ('card', 'Card'), ('cash', 'Cash')], default='cash', max_length=50),
        ),
    ]
