# Generated by Django 5.2.10 on 2026-01-28 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_todaysspecial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodaysSpecial',
        ),
    ]
