# Generated by Django 5.1.3 on 2025-10-27 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_seat_is_occupied'),
        ('userapp', '0008_orderitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='food_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.category'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.menuitem'),
        ),
    ]
