# Generated by Django 5.1.3 on 2025-11-17 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_userreport_userreportimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreportimage',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='userapp.userreport'),
        ),
    ]
