# Generated by Django 5.1.3 on 2025-10-27 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_seat_is_occupied'),
        ('userapp', '0009_orderitem_food_name_alter_orderitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblmenuitem'),
        ),
    ]
