# Generated by Django 5.2.10 on 2026-02-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_delete_todaysspecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booking_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='booking_type',
            field=models.CharField(blank=True, choices=[('TABLE_ONLY', 'Table Only'), ('PREBOOKED', 'Prebooked (Table + Food)'), ('ONSPOT', 'On-the-Spot (Table + Food)')], max_length=25, null=True),
        ),
    ]
