# Generated by Django 5.1.3 on 2025-10-27 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_alter_orderitem_food_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_content', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='report_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.tbl_register')),
            ],
        ),
    ]
