# Generated by Django 5.1.3 on 2025-10-27 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_seat_is_occupied'),
        ('userapp', '0011_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='category',
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.category'),
            preserve_default=False,
        ),
    ]
