# Generated by Django 5.2.10 on 2026-02-13 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_migrate_todays_special_to_menuitem'),
        ('userapp', '0011_alter_order_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.menuitem'),
        ),
    ]
