# Generated by Django 5.2.10 on 2026-02-20 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_migrate_todays_special_to_menuitem'),
        ('userapp', '0012_alter_orderitem_food_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.timeslot'),
        ),
    ]
