# Generated by Django 5.1.3 on 2025-10-27 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_seat_is_occupied'),
        ('userapp', '0012_remove_orderitem_category_order_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblmenuitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='food_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
