# Generated by Django 5.1.4 on 2025-10-29 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_seat_is_occupied'),
        ('userapp', '0014_order_booking_type_order_food_item_order_food_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.tbldailymenu'),
        ),
    ]
