# Generated by Django 5.2.10 on 2026-02-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_alter_order_food_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='food_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refund_initiated', 'Refund Initiated'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refund_initiated', 'Refund Initiated'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
