# Generated by Django 5.1.4 on 2025-10-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_seat_is_occupied'),
        ('userapp', '0016_remove_order_food_item_remove_order_food_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='seats',
            field=models.ManyToManyField(blank=True, related_name='seat_orders', to='adminapp.seat'),
        ),
    ]
