# Generated by Django 5.1.4 on 2025-10-29 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_seat_is_occupied'),
        ('userapp', '0017_alter_order_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seats',
        ),
        migrations.CreateModel(
            name='OrderSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_seats', to='userapp.order')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.seat')),
            ],
        ),
    ]
