# Generated by Django 5.1.4 on 2025-10-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_alter_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table',
        ),
        migrations.AddField(
            model_name='order',
            name='tables',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
